---
name: Z-Wave JS UI Secondary
version: dev
slug: zwavejs2mqtt_sec
description: Fully configurable Z-Wave JS gateway and control panel
url: https://github.com/sirfixalotgk/addon-zwave-js-ui-secondary
codenotary: codenotary@frenck.dev
ingress: true
ingress_stream: true
panel_title: Z-Wave JS Secondary
panel_icon: mdi:z-wave
startup: system
init: false
timeout: 30
arch:
  - aarch64
  - amd64
  - armv7
discovery:
  - zwave_js
services:
  - mqtt:want
uart: true
udev: true
map:
  - share:rw
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
ports:
  3030/tcp: null
ports_description:
  3030/tcp: Z-Wave JS communication
